name: Common Test

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  linux:
    name: Test on OTP ${{ matrix.combo.otp-version }} and ${{ matrix.combo.os }}
    runs-on: ${{ matrix.combo.os }}

    strategy:
      fail-fast: false
      matrix:
        combo:
          - os: 'ubuntu-latest'
            otp-version: '25'
            rebar3-version: '3.23'
          - os: 'ubuntu-latest'
            otp-version: '26'
            rebar3-version: '3.23'
          - os: 'ubuntu-latest'
            otp-version: '27'
            rebar3-version: '3.24'

    steps:
    - uses: GuillaumeFalourd/setup-rsync@v1.2
      id: rsync
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.combo.otp-version }}
        rebar3-version: ${{ matrix.combo.rebar3-version }}
    - name: Compile
      run: make compile
    - name: Test
      run: make ci
    - name: Upload CT logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ct-logs-otp-${{ matrix.combo.otp-version }}-${{ github.run_id }}
        path: _build/test/logs/
        retention-days: 5
